# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Qu Pingzhe's Blog
author: Qu Pingzhe
#email: your-email@domain.com
description: 个人博客
baseurl: "" # the subpath of your site, e.g. /blog
url: https://qupingzhe.github.io
github_username:  qupingzhe
# Build settings
markdown: kramdown
#kramdown:
    #syntax_highlighter: rouge
#theme: minima
#highlighter: rouge
#plugins:
  #- jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
color: RGB(234, 234, 234)
excerpt_separator: "<!--more-->"
ASSETS: /assets
LATEST_SIZE: 4
